### ISSUE TITLE
Optimize energy consumption

### ISSUE THREAD

**Issue by Lucidiot** [MiniVP/Aura#1]
* Disable unused Arduino features
* Try to reduce the CPU frequency

See http://home-automation-community.com/arduino-low-power-how-to-run-atmega328p-for-a-year-on-coin-cell-battery/

**Comment by valentintintin** [comment]
http://www.fiz-ix.com/2012/11/save-power-by-disabling-arduino-peripherals/

**Comment by valentintintin** [comment]
ADC désactivé au prix du suivis du voltage de l'Arduino.
J'aurais pu enlever les LEDs mais c'est pas simple avec mes gros doigts.
